@echo off
echo Starting ChendAI Studio...
echo.
echo [1/2] Starting Vite Dev Server...
start "Vite Dev Server" cmd /k "cd /d %~dp0 && npm run dev:react"
timeout /t 5 /nobreak >nul
echo.
echo [2/2] Starting Electron App...
start "Electron App" cmd /k "cd /d %~dp0 && npm run dev:electron"
echo.
echo ChendAI Studio is starting...
echo Check the other windows for output.
